In [1]:
import pandas as pd

In [20]:
df1=pd.read_csv("crop area (hectares).csv")

In [21]:
df2=pd.read_csv("features.csv")

In [22]:
df3=pd.read_csv("features2.csv")

In [23]:
df4=pd.read_csv("irrigation coverage (%).csv")

In [24]:
df5=pd.read_csv("yield.csv")

In [25]:
df1.columns.to_list()

['Unnamed: 0', 'Year', 'State Name', 'Dist Name', 'Crop_Area_ha']

In [26]:
df2.columns.to_list()

['Unnamed: 0',
 'Year',
 'State Name',
 'Dist Name',
 'soil_moisture_level_percent',
 'pesticide_usage_kg_per_hectare',
 'altitude_meters',
 'farming_mechanization_score']

In [27]:
df3.columns.to_list()

['Unnamed: 0',
 'Year',
 'State Name',
 'Dist Name',
 'Area_ha',
 'Yield_kg_per_ha',
 'N_req_kg_per_ha',
 'P_req_kg_per_ha',
 'K_req_kg_per_ha',
 'Total_N_kg',
 'Total_P_kg',
 'Total_K_kg',
 'Temperature_C',
 'Humidity_%',
 'pH',
 'Rainfall_mm',
 'Wind_Speed_m_s',
 'Solar_Radiation_MJ_m2_day']

In [28]:
df4.columns.to_list()

['Unnamed: 0', 'Year', 'State Name', 'Dist Name', 'Total_Irrigation(1000 ha)']

In [29]:
df5.columns.to_list()

['Unnamed: 0',
 'Year',
 'State Name',
 'Dist Name',
 'Total_Area_ha',
 'Total_Yield_t_per_ha']

In [34]:
def clean_dataset(data):
    # 1. Drop common "trash" index columns
    data = data.drop(columns=['index', 'level_0'], errors='ignore')
    
    # 2. Drop any column that starts with "Unnamed" (common in CSV exports)
    data = data.loc[:, ~data.columns.str.contains('^Unnamed', case=False)]
    
    # 3. Ensure Year/State/District stay as regular columns, not an Index
    data = data.reset_index(drop=True)
    
    return data

In [35]:
# Clean all dataframes in a loop
df1 = clean_dataset(df1)
df2 = clean_dataset(df2)
df3 = clean_dataset(df3)
df4 = clean_dataset(df4)
df5 = clean_dataset(df5)

In [36]:
from functools import reduce

# List of your cleaned dataframes
dfs = [df1, df2, df3, df4, df5]

# Merge them all on the common columns
df = reduce(lambda left, right: pd.merge(left, right, on=['Year', 'State Name', 'Dist Name'], how='inner'), dfs)

# Final check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42735 entries, 0 to 42734
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Year                            42735 non-null  int64
 1   State Name                      42735 non-null  object
 2   Dist Name                       42735 non-null  object
 3   Crop_Area_ha                    42735 non-null  float64
 4   soil_moisture_level_percent     42735 non-null  float64
 5   pesticide_usage_kg_per_hectare  42735 non-null  float64
 6   altitude_meters                 42735 non-null  float64
 7   farming_mechanization_score     42735 non-null  float64
 8   Area_ha                         42735 non-null  float64
 9   Yield_kg_per_ha                 42735 non-null  float64
 10  N_req_kg_per_ha                 42735 non-null  float64
 11  P_req_kg_per_ha                 42735 non-null  float64
 12  K_req_kg_per_ha                 42735 non-null  float64
 13  Total_N_kg                      42735 non-null  float64
 14  Total_P_kg                      42735 non-null  float64
 15  Total_K_kg                      42735 non-null  float64
 16  Temperature_C                   42735 non-null  float64
 17  Humidity_%                      42735 non-null  float64
 18  pH                              42735 non-null  float64
 19  Rainfall_mm                     42735 non-null  float64
 20  Wind_Speed_m_s                  42735 non-null  float64
 21  Solar_Radiation_MJ_m2_day       42735 non-null  float64
 22  Total_Irrigation(1000 ha)       42735 non-null  float64
 23  Total_Area_ha                   42735 non-null  float64
 24  Total_Yield_t_per_ha            42735 non-null  float64
dtypes: float64(22), int64(1), object(2)
memory usage: 8.2+ MB

In [37]:
df.head()

,Year,State Name,Dist Name,Crop_Area_ha,soil_moisture_level_percent,pesticide_usage_kg_per_hectare,altitude_meters,farming_mechanization_score,Area_ha,Yield_kg_per_ha,...,Total_K_kg,Temperature_C,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Solar_Radiation_MJ_m2_day,Total_Irrigation(1000 ha),Total_Area_ha,Total_Yield_t_per_ha
0,1966,Chhattisgarh,Durg,993200.0,31.476999,2.604451,296.574626,65.062861,201666.666667,501.420000,...,1.529995e+06,22.333333,70.0,6.333333,866.666667,2.0,18.0,3.7975,931590.0,0.276087
1,1966,Chhattisgarh,Durg,993200.0,27.032150,2.999402,10.000000,34.360686,201666.666667,501.420000,...,1.529995e+06,22.333333,70.0,6.333333,866.666667,2.0,18.0,3.7975,931590.0,0.276087
2,1966,Chhattisgarh,Durg,993200.0,32.533820,1.837156,302.155906,74.779958,201666.666667,501.420000,...,1.529995e+06,22.333333,70.0,6.333333,866.666667,2.0,18.0,3.7975,931590.0,0.276087
3,1967,Chhattisgarh,Durg,1014000.0,38.661209,1.635120,340.220755,67.209165,200666.666667,678.723333,...,3.106314e+06,22.333333,70.0,6.333333,866.666667,2.0,18.0,5.1930,1216430.0,0.417204
4,1967,Chhattisgarh,Durg,1014000.0,26.360926,1.091924,244.109476,44.357385,200666.666667,678.723333,...,3.106314e+06,22.333333,70.0,6.333333,866.666667,2.0,18.0,5.1930,1216430.0,0.417204

In [38]:
df.to_csv("semi_final.csv")

In [47]:
df=pd.read_csv("final_dataset.csv")

In [48]:
# Remove any column that isn't actual data
cols_to_drop = [c for c in df.columns if 'index' in c.lower() or 'unnamed' in c.lower()]
df.drop(columns=cols_to_drop, inplace=True)

In [49]:
df.head()

,Year,State Name,Dist Name,Crop_Area_ha,soil_moisture_level_percent,pesticide_usage_kg_per_hectare,altitude_meters,farming_mechanization_score,Area_ha,Yield_kg_per_ha,...,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Total_Irrigation(1000 ha),Total_Area_ha,Total_Yield_t_per_ha,Fertilizer_Usage_kg_per_hectare,Groundwater_Level_m,Historical_Yield_Variance
0,1966,Chhattisgarh,Durg,993200.0,31.476999,2.604451,296.574626,65.062861,201666.666667,501.420000,...,70.0,6.333333,866.666667,2.0,3.7975,931590.0,0.276087,32.431222,40.463796,0.046730
1,1966,Chhattisgarh,Durg,993200.0,27.032150,2.999402,10.000000,34.360686,201666.666667,501.420000,...,70.0,6.333333,866.666667,2.0,3.7975,931590.0,0.276087,37.055096,30.906599,0.058345
2,1966,Chhattisgarh,Durg,993200.0,32.533820,1.837156,302.155906,74.779958,201666.666667,501.420000,...,70.0,6.333333,866.666667,2.0,3.7975,931590.0,0.276087,35.299836,34.892015,0.022879
3,1967,Chhattisgarh,Durg,1014000.0,38.661209,1.635120,340.220755,67.209165,200666.666667,678.723333,...,70.0,6.333333,866.666667,2.0,5.1930,1216430.0,0.417204,48.361984,34.524686,0.053957
4,1967,Chhattisgarh,Durg,1014000.0,26.360926,1.091924,244.109476,44.357385,200666.666667,678.723333,...,70.0,6.333333,866.666667,2.0,5.1930,1216430.0,0.417204,43.343154,37.494183,0.042168

In [50]:
df.describe()

,Year,Crop_Area_ha,soil_moisture_level_percent,pesticide_usage_kg_per_hectare,altitude_meters,farming_mechanization_score,Area_ha,Yield_kg_per_ha,N_req_kg_per_ha,P_req_kg_per_ha,...,Humidity_%,pH,Rainfall_mm,Wind_Speed_m_s,Total_Irrigation(1000 ha),Total_Area_ha,Total_Yield_t_per_ha,Fertilizer_Usage_kg_per_hectare,Groundwater_Level_m,Historical_Yield_Variance
count,42735.000000,4.273500e+04,42735.000000,42735.000000,42735.000000,42735.000000,42735.000000,42735.000000,42735.000000,42735.000000,...,42735.000000,42735.000000,42735.000000,42735.000000,42735.000000,4.273500e+04,42735.000000,42735.000000,42735.000000,42735.000000
mean,1991.736609,4.749712e+05,28.005121,1.803829,315.298490,54.962223,58625.050427,1173.963462,28.901585,13.677611,...,69.422838,6.283480,847.045747,2.156160,10.589681,7.200617e+05,1.245602,81.861647,30.305065,0.174248
std,14.928252,2.770369e+05,6.972617,0.598424,223.818844,19.168021,49319.819416,623.662187,15.713985,7.345342,...,2.043245,0.061172,63.816963,0.146954,11.155706,4.490812e+05,0.763084,44.283874,4.425031,0.125539
min,1966.000000,-6.000000e+03,10.000000,0.300000,10.000000,15.000000,10.000000,8.000000,0.144000,0.080000,...,60.000000,6.000000,600.000000,1.500000,-1.000000,-1.989000e+04,-1.773256,0.487974,8.518879,-0.354887
25%,1979.000000,2.994600e+05,23.235200,1.399773,131.083246,41.463977,24233.333333,751.533333,18.148720,8.663517,...,68.750000,6.250000,825.000000,2.000000,2.666000,4.378100e+05,0.714022,51.576576,27.471920,0.087803
50%,1992.000000,4.271200e+05,28.003920,1.802931,299.546806,54.985441,45300.000000,1048.550000,25.561170,12.129967,...,68.750000,6.250000,825.000000,2.250000,7.737400,6.285800e+05,1.055512,72.456605,30.366032,0.141274
75%,2005.000000,5.783000e+05,32.745004,2.207016,467.825620,68.369629,77700.000000,1458.826667,35.876217,17.033530,...,70.000000,6.333333,866.666667,2.250000,14.967500,8.937000e+05,1.569392,101.951464,33.218945,0.224006
max,2017.000000,1.792430e+06,50.000000,4.056093,1440.528681,95.000000,368500.000000,20280.966667,372.292307,204.462507,...,80.000000,6.500000,1200.000000,3.000000,93.051450,3.048780e+06,6.674434,1157.546456,48.359036,1.315604

In [52]:
# 1. Define the columns that must stay at the start
fixed_cols = ['Year', 'State Name', 'Dist Name']

# 2. Get all other columns and sort them alphabetically
other_cols = sorted([c for c in df.columns if c not in fixed_cols])

# 3. Reorder the DataFrame
df = df[fixed_cols + other_cols]

In [53]:
df.head()

,Year,State Name,Dist Name,Area_ha,Crop_Area_ha,Fertilizer_Usage_kg_per_hectare,Groundwater_Level_m,Historical_Yield_Variance,Humidity_%,K_req_kg_per_ha,...,Total_N_kg,Total_P_kg,Total_Yield_t_per_ha,Wind_Speed_m_s,Yield_kg_per_ha,altitude_meters,farming_mechanization_score,pH,pesticide_usage_kg_per_hectare,soil_moisture_level_percent
0,1966,Chhattisgarh,Durg,201666.666667,993200.0,32.431222,40.463796,0.046730,70.0,9.253457,...,1.721661e+06,8.379973e+05,0.276087,2.0,501.420000,296.574626,65.062861,6.333333,2.604451,31.476999
1,1966,Chhattisgarh,Durg,201666.666667,993200.0,37.055096,30.906599,0.058345,70.0,9.253457,...,1.721661e+06,8.379973e+05,0.276087,2.0,501.420000,10.000000,34.360686,6.333333,2.999402,27.032150
2,1966,Chhattisgarh,Durg,201666.666667,993200.0,35.299836,34.892015,0.022879,70.0,9.253457,...,1.721661e+06,8.379973e+05,0.276087,2.0,501.420000,302.155906,74.779958,6.333333,1.837156,32.533820
3,1967,Chhattisgarh,Durg,200666.666667,1014000.0,48.361984,34.524686,0.053957,70.0,12.880633,...,3.525311e+06,1.697989e+06,0.417204,2.0,678.723333,340.220755,67.209165,6.333333,1.635120,38.661209
4,1967,Chhattisgarh,Durg,200666.666667,1014000.0,43.343154,37.494183,0.042168,70.0,12.880633,...,3.525311e+06,1.697989e+06,0.417204,2.0,678.723333,244.109476,44.357385,6.333333,1.091924,26.360926

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42735 entries, 0 to 42734
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Year                             42735 non-null  int64
 1   State Name                       42735 non-null  object
 2   Dist Name                        42735 non-null  object
 3   Area_ha                          42735 non-null  float64
 4   Crop_Area_ha                     42735 non-null  float64
 5   Fertilizer_Usage_kg_per_hectare  42735 non-null  float64
 6   Groundwater_Level_m              42735 non-null  float64
 7   Historical_Yield_Variance        42735 non-null  float64
 8   Humidity_%                       42735 non-null  float64
 9   K_req_kg_per_ha                  42735 non-null  float64
 10  N_req_kg_per_ha                  42735 non-null  float64
 11  P_req_kg_per_ha                  42735 non-null  float64
 12  Rainfall_mm                      42735 non-null  float64
 13  Temperature_C                    42735 non-null  float64
 14  Total_Area_ha                    42735 non-null  float64
 15  Total_Irrigation(1000 ha)        42735 non-null  float64
 16  Total_K_kg                       42735 non-null  float64
 17  Total_N_kg                       42735 non-null  float64
 18  Total_P_kg                       42735 non-null  float64
 19  Total_Yield_t_per_ha             42735 non-null  float64
 20  Wind_Speed_m_s                   42735 non-null  float64
 21  Yield_kg_per_ha                  42735 non-null  float64
 22  altitude_meters                  42735 non-null  float64
 23  farming_mechanization_score      42735 non-null  float64
 24  pH                               42735 non-null  float64
 25  pesticide_usage_kg_per_hectare   42735 non-null  float64
 26  soil_moisture_level_percent      42735 non-null  float64
dtypes: float64(24), int64(1), object(2)
memory usage: 8.8+ MB

In [57]:
df.isna().sum()

Year                               0
State Name                         0
Dist Name                          0
Area_ha                            0
Crop_Area_ha                       0
Fertilizer_Usage_kg_per_hectare    0
Groundwater_Level_m                0
Historical_Yield_Variance          0
Humidity_%                         0
K_req_kg_per_ha                    0
N_req_kg_per_ha                    0
P_req_kg_per_ha                    0
Rainfall_mm                        0
Temperature_C                      0
Total_Area_ha                      0
Total_Irrigation(1000 ha)          0
Total_K_kg                         0
Total_N_kg                         0
Total_P_kg                         0
Total_Yield_t_per_ha               0
Wind_Speed_m_s                     0
Yield_kg_per_ha                    0
altitude_meters                    0
farming_mechanization_score        0
pH                                 0
pesticide_usage_kg_per_hectare     0
soil_moisture_level_percent        0
dtype: int64

In [60]:
df.to_csv("Final_Final_Dataset.csv")